import { IngredientForm } from '@/components/ingredient-form';
import { ChefHat } from 'lucide-react';

export default function Home() {
  return (
    <div className="flex flex-col min-h-dvh bg-background text-foreground">
      <header className="py-6 px-4 sm:px-6 border-b border-border/50">
        <div className="container mx-auto flex items-center gap-3">
          <div className="bg-primary/20 text-primary p-2 rounded-lg">
            <ChefHat className="w-7 h-7" />
          </div>
          <h1 className="text-3xl font-bold font-headline text-foreground">
            Fridge Chef
          </h1>
        </div>
      </header>
      <main className="flex-grow">
        <IngredientForm />
      </main>
      <footer className="text-center p-6 text-sm text-muted-foreground">
        Generated by Fridge Chef AI
      </footer>
    </div>
  );
}
